wandb_version: 1

VERSION:
  desc: null
  value: 2
MODEL:
  desc: null
  value:
    LOAD_PROPOSALS: false
    MASK_ON: true
    KEYPOINT_ON: false
    DEVICE: cuda
    META_ARCHITECTURE: SamDetector
    WEIGHTS: mobile_sam.pt
    PIXEL_MEAN:
    - 123.675
    - 116.28
    - 103.53
    PIXEL_STD:
    - 58.395
    - 57.12
    - 57.375
    BACKBONE:
      NAME: build_sam_vit_det_backbone
      FREEZE_AT: 2
      TYPE: vit_t
    FPN:
      IN_FEATURES: []
      OUT_CHANNELS: 256
      NORM: LN
      FUSE_TYPE: sum
      INNER_CHANNELS: 32
      UP_SAMPLE_SCALE: 4
      ANCHOR_STRIDE:
      - 4
      - 8
      - 16
      - 32
      - 64
      SELECTED_CHANNELS:
      - 8
      - 10
      - 12
      - 14
      - 16
      - 18
      - 20
      - 22
      - 24
      - 26
      - 28
      - 30
      IN_CHANNELS:
      - 256
    PROPOSAL_GENERATOR:
      NAME: RPN
      MIN_SIZE: 0
    ANCHOR_GENERATOR:
      NAME: DefaultAnchorGenerator
      SIZES:
      - - 32
      - - 64
      - - 128
      - - 256
      - - 512
      ASPECT_RATIOS:
      - - 0.5
        - 1.0
        - 2.0
      ANGLES:
      - - -90
        - 0
        - 90
      OFFSET: 0.0
    RPN:
      HEAD_NAME: StandardRPNHead
      IN_FEATURES:
      - feat4
      - feat3
      - feat2
      - feat1
      - feat0
      BOUNDARY_THRESH: -1
      IOU_THRESHOLDS:
      - 0.3
      - 0.7
      IOU_LABELS:
      - 0
      - -1
      - 1
      BATCH_SIZE_PER_IMAGE: 512
      POSITIVE_FRACTION: 0.5
      BBOX_REG_LOSS_TYPE: smooth_l1
      BBOX_REG_LOSS_WEIGHT: 1.0
      BBOX_REG_WEIGHTS:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      SMOOTH_L1_BETA: 0.0
      LOSS_WEIGHT: 1.0
      PRE_NMS_TOPK_TRAIN: 2000
      PRE_NMS_TOPK_TEST: 1000
      POST_NMS_TOPK_TRAIN: 1000
      POST_NMS_TOPK_TEST: 1000
      NMS_THRESH: 0.7
      CONV_DIMS:
      - -1
    ROI_HEADS:
      NAME: samAnchorPromptRoiHeads
      NUM_CLASSES: 80
      IN_FEATURES:
      - feat4
      - feat3
      - feat2
      - feat1
      IOU_THRESHOLDS:
      - 0.5
      IOU_LABELS:
      - 0
      - 1
      BATCH_SIZE_PER_IMAGE: 256
      POSITIVE_FRACTION: 0.25
      SCORE_THRESH_TEST: 0.02
      NMS_THRESH_TEST: 0.5
      PROPOSAL_APPEND_GT: true
      ALLOW_LOW_QUALITY_MATCHES: true
    ROI_BOX_HEAD:
      NAME: FastRCNNConvFCHead
      BBOX_REG_LOSS_TYPE: smooth_l1
      BBOX_REG_LOSS_WEIGHT: 1.0
      BBOX_REG_WEIGHTS:
      - 10.0
      - 10.0
      - 5.0
      - 5.0
      SMOOTH_L1_BETA: 0.0
      POOLER_RESOLUTION: 7
      POOLER_SAMPLING_RATIO: 0
      POOLER_TYPE: ROIAlignV2
      NUM_FC: 2
      FC_DIM: 1024
      NUM_CONV: 0
      CONV_DIM: 256
      NORM: ''
      CLS_AGNOSTIC_BBOX_REG: false
      TRAIN_ON_PRED_BOXES: true
      USE_FED_LOSS: false
      USE_SIGMOID_CE: false
      FED_LOSS_FREQ_WEIGHT_POWER: 0.5
      FED_LOSS_NUM_CLASSES: 50
    ROI_BOX_CASCADE_HEAD:
      BBOX_REG_WEIGHTS:
      - - 10.0
        - 10.0
        - 5.0
        - 5.0
      - - 20.0
        - 20.0
        - 10.0
        - 10.0
      - - 30.0
        - 30.0
        - 15.0
        - 15.0
      IOUS:
      - 0.5
      - 0.6
      - 0.7
    ROI_MASK_HEAD:
      NAME: samMaskHead
      POOLER_RESOLUTION: 14
      POOLER_SAMPLING_RATIO: 0
      NUM_CONV: 4
      CONV_DIM: 256
      NORM: ''
      CLS_AGNOSTIC_MASK: true
      POOLER_TYPE: ROIAlignV2
      WITH_SINCOS: true
      MASK_LOSS_TYPE: ce
      MASK_LOSS_WEIGHT: 1.0
      PER_QUERY_POINT: 4
    ROI_KEYPOINT_HEAD:
      NAME: KRCNNConvDeconvUpsampleHead
      POOLER_RESOLUTION: 14
      POOLER_SAMPLING_RATIO: 0
      CONV_DIMS:
      - 512
      - 512
      - 512
      - 512
      - 512
      - 512
      - 512
      - 512
      NUM_KEYPOINTS: 17
      MIN_KEYPOINTS_PER_IMAGE: 1
      NORMALIZE_LOSS_BY_VISIBLE_KEYPOINTS: true
      LOSS_WEIGHT: 1.0
      POOLER_TYPE: ROIAlignV2
    SEM_SEG_HEAD:
      NAME: SemSegFPNHead
      IN_FEATURES:
      - p2
      - p3
      - p4
      - p5
      IGNORE_VALUE: 255
      NUM_CLASSES: 54
      CONVS_DIM: 128
      COMMON_STRIDE: 4
      NORM: GN
      LOSS_WEIGHT: 1.0
    PANOPTIC_FPN:
      INSTANCE_LOSS_WEIGHT: 1.0
      COMBINE:
        ENABLED: true
        OVERLAP_THRESH: 0.5
        STUFF_AREA_LIMIT: 4096
        INSTANCES_CONFIDENCE_THRESH: 0.5
    RETINANET:
      NUM_CLASSES: 80
      IN_FEATURES:
      - p3
      - p4
      - p5
      - p6
      - p7
      NUM_CONVS: 4
      IOU_THRESHOLDS:
      - 0.4
      - 0.5
      IOU_LABELS:
      - 0
      - -1
      - 1
      PRIOR_PROB: 0.01
      SCORE_THRESH_TEST: 0.05
      TOPK_CANDIDATES_TEST: 1000
      NMS_THRESH_TEST: 0.5
      BBOX_REG_WEIGHTS:
      - 1.0
      - 1.0
      - 1.0
      - 1.0
      FOCAL_LOSS_GAMMA: 2.0
      FOCAL_LOSS_ALPHA: 0.25
      SMOOTH_L1_LOSS_BETA: 0.1
      BBOX_REG_LOSS_TYPE: smooth_l1
      NORM: ''
    RESNETS:
      DEPTH: 50
      OUT_FEATURES:
      - res4
      NUM_GROUPS: 1
      NORM: FrozenBN
      WIDTH_PER_GROUP: 64
      STRIDE_IN_1X1: true
      RES5_DILATION: 1
      RES2_OUT_CHANNELS: 256
      STEM_OUT_CHANNELS: 64
      DEFORM_ON_PER_STAGE:
      - false
      - false
      - false
      - false
      DEFORM_MODULATED: false
      DEFORM_NUM_GROUPS: 1
    CONFIGS:
      ONLY_DECODER: false
INPUT:
  desc: null
  value:
    MIN_SIZE_TRAIN:
    - 800
    MIN_SIZE_TRAIN_SAMPLING: choice
    MAX_SIZE_TRAIN: 1333
    MIN_SIZE_TEST: 800
    MAX_SIZE_TEST: 1333
    RANDOM_FLIP: horizontal
    CROP:
      ENABLED: false
      TYPE: relative_range
      SIZE:
      - 0.9
      - 0.9
    FORMAT: RGB
    MASK_FORMAT: bitmask
    PROMPT_SIZE:
    - 90
    - 4
    CUSTOM_AUG: ResizeLongestSize
    TRAIN_SIZE: 1024
    TEST_SIZE: 1024
    SCALE_RANGE:
    - 0.1
    - 2.0
    TEST_INPUT_TYPE: ResizeLongestSize
    PAD_MASK: true
    MASK_PAD_VAL: 0.0
DATASETS:
  desc: null
  value:
    TRAIN:
    - coco_2017_train
    PROPOSAL_FILES_TRAIN: []
    PRECOMPUTED_PROPOSAL_TOPK_TRAIN: 2000
    TEST:
    - coco_2017_val
    PROPOSAL_FILES_TEST: []
    PRECOMPUTED_PROPOSAL_TOPK_TEST: 1000
DATALOADER:
  desc: null
  value:
    NUM_WORKERS: 16
    ASPECT_RATIO_GROUPING: true
    SAMPLER_TRAIN: TrainingSampler
    REPEAT_THRESHOLD: 0.0
    FILTER_EMPTY_ANNOTATIONS: true
    PERSISTENT_WORKERS: false
SOLVER:
  desc: null
  value:
    LR_SCHEDULER_NAME: WarmupMultiStepLR
    MAX_ITER: 90000
    BASE_LR: 0.0002
    BASE_LR_END: 0.0
    MOMENTUM: 0.9
    NESTEROV: false
    WEIGHT_DECAY: 0.001
    WEIGHT_DECAY_NORM: 0.0
    GAMMA: 0.1
    STEPS:
    - 60000
    - 80000
    NUM_DECAYS: 3
    WARMUP_FACTOR: 0.0001
    WARMUP_ITERS: 100
    WARMUP_METHOD: linear
    RESCALE_INTERVAL: false
    CHECKPOINT_PERIOD: 5000
    IMS_PER_BATCH: 2
    REFERENCE_WORLD_SIZE: 0
    BIAS_LR_FACTOR: 1.0
    WEIGHT_DECAY_BIAS: null
    CLIP_GRADIENTS:
      ENABLED: false
      CLIP_TYPE: value
      CLIP_VALUE: 1.0
      NORM_TYPE: 2.0
    AMP:
      ENABLED: true
    OPTIMIZER: ADAMW
    USE_CUSTOM_SOLVER: true
    LOGGER_FREQ: 20
TEST:
  desc: null
  value:
    EXPECTED_RESULTS: []
    EVAL_PERIOD: 5000
    KEYPOINT_OKS_SIGMAS: []
    DETECTIONS_PER_IMAGE: 300
    AUG:
      ENABLED: false
      MIN_SIZES:
      - 400
      - 500
      - 600
      - 700
      - 800
      - 900
      - 1000
      - 1100
      - 1200
      MAX_SIZE: 4000
      FLIP: true
    PRECISE_BN:
      ENABLED: false
      NUM_ITER: 200
    MASK_THR_BINARY: 0.5
    DO_POSTPROCESS: true
    IMS_PER_BATCH: 2
OUTPUT_DIR:
  desc: null
  value: ./output/full_tune_tiny
SEED:
  desc: null
  value: -1
CUDNN_BENCHMARK:
  desc: null
  value: false
VIS_PERIOD:
  desc: null
  value: 0
GLOBAL:
  desc: null
  value:
    HACK: 1.0
FIND_UNUSED_PARAM:
  desc: null
  value: true
FP16:
  desc: null
  value: true
_wandb:
  desc: null
  value:
    python_version: 3.8.18
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1697890232.94478
    t:
      1:
      - 1
      - 41
      - 43
      - 49
      - 55
      - 63
      2:
      - 1
      - 41
      - 43
      - 49
      - 55
      - 63
      3:
      - 16
      - 23
      4: 3.8.18
      5: 0.15.12
      8:
      - 5
      - 9
      13: linux-x86_64
