_BASE_: "Base/Base_Fvlm_coco_1x.yaml"
MODEL:
  BACKBONE:
    TYPE: "RN50"
  CLIP_TEXT_FEATS_PATH: "datasets/coco/embeddings/resnet_50/coco_embed_80.npy"
  FPN: 
    NORM: "SyncBN" # 'SyncBN'  or ""
    ADD_PE: False
  RPN:
    HEAD_NAME: 'CustomStandardRPNHead'
    CONV_DIMS: (256,256)
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512 
    SCORE_THRESH_TEST: 0.02
    NUM_CLASSES: 48 # num of seen classes
  ROI_BOX_HEAD:
    NAME: 'CustomFastRCNNConvFCHead'
    NUM_FC: 1
    NUM_CONV: 4
    BACKGROUND_WEIGHT: 0.2
    CAT_FREQ_PATH: ''
    USE_SIGMOID_CE: False
    NORM: 'SyncBN'
  ROI_MASK_HEAD:
    NAME: 'CustomMaskRCNNConvUpsampleHead'
    NORM: 'SyncBN'
DATASETS:
  TRAIN: ("coco_zeroshot_train",)
DATALOADER:
  NUM_WORKERS: 16 # num_workers == batchsize_per_gpu
SOLVER:
  IMS_PER_BATCH: 64  # change  # max 8 imgs per batch
  BASE_LR: 0.02  # change0.000025
  MAX_ITER: 11250
  CHECKPOINT_PERIOD: 10000  #  change
  OPTIMIZER: 'SGD'
  WEIGHT_DECAY: 0.01
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  WARMUP_FACTOR: 0.01
  WARMUP_METHOD: "linear"
  WARMUP_ITERS: 1000
  STEPS: (10125, 10688, 10869)
  GAMMA: 0.1
  MOMENTUM: 0.9
TEST:
  EVAL_PERIOD: 900000000 # change
  IMS_PER_BATCH: 1 #every gpu has most 2 images  # change
OUTPUT_DIR: 'output/clipRpn'
FP16: True