_BASE_: "Base/Base_Fvlm_lvis_1x.yaml"
MODEL:
  BACKBONE:
    TYPE: "RN50"
  CLIP_TEXT_FEATS_PATH: "datasets/lvis/lvis_cls.pkl" #********
  FPN: 
    NORM: "SyncBN" # 'SyncBN'   or ""
    ADD_PE: False
  RPN:
    HEAD_NAME: 'CustomStandardRPNHead'
    CONV_DIMS: (256,256)
    BATCH_SIZE_PER_IMAGE: 256 # the sampling num 
    BBOX_REG_LOSS_TYPE: 'huber'
  PROPOSAL_GENERATOR:
    NAME: 'CustomRPN'
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 512 
    NUM_CLASSES: 866
  ROI_BOX_HEAD:
    NAME: 'CustomFastRCNNConvFCHead'
    NUM_FC: 1
    NUM_CONV: 4
    BACKGROUND_WEIGHT: 0.9
    CAT_FREQ_PATH: ''
    USE_SIGMOID_CE: False
    USE_FED_LOSS: False
    NORM: 'SyncBN'
  ROI_MASK_HEAD:
    NORM: 'SyncBN'
    NAME: "CustomMaskRCNNConvUpsampleHead"
  NUM_SAMPLE_CATS: 50
DATASETS:
  TRAIN: ("lvis_v1_zeroshot_train",)
  TEST: ("lvis_v1_val",)
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.001
  NUM_WORKERS: 16 # num_workers == batchsize_per_gpu
SOLVER:
  # IMS_PER_BATCH: 256  # change  # max 8 imgs per batch
  # BASE_LR: 0.36  # change0.000025
  # MAX_ITER: 46100  
  # WARMUP_FACTOR: 0.889
  # WARMUP_ITERS: 1000
  IMS_PER_BATCH: 64  # change  # max 8 imgs per batch
  BASE_LR: 0.08  # change0.000025
  MAX_ITER: 184400  
  WARMUP_FACTOR: 0.04
  WARMUP_ITERS: 1000
  STEPS: (147520, 169560, 178980)
  CHECKPOINT_PERIOD: 90000000  #  change
  OPTIMIZER: 'SGD'
  WARMUP_METHOD: "linear" 
  WEIGHT_DECAY: 0.0001
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  GAMMA: 0.1
  MOMENTUM: 0.9
INPUT:
  CLIP_TRAIN_SIZE: 1024
  CUSTOM_AUG: ResizeLongLSJ  #!!!!
OUTPUT_DIR: './output/clipRpn/FVLM_Lvis'