_BASE_: "Fvlm_coco.yaml"
MODEL:
  BACKBONE:
    TYPE: "RN50"
  CLIP_TEXT_FEATS_PATH: "datasets/coco/coco_cls.pkl"
  WEIGHTS: ""
  RPN:
    HEAD_NAME: "StandardRPNHead"
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NMS_THRESH_TEST: 0.4
    BATCH_SIZE_PER_IMAGE: 512 
    SCORE_THRESH_TEST: 0.02
    NUM_CLASSES: 80 # num of seen classes
  ROI_BOX_HEAD:
    CAT_FREQ_PATH: 'datasets/coco/zero-shot/instances_train2017_seen_2_oriorder_cat_info.json'
    BASE_ALPHA: 0.2
    NOVEL_BETA: 0.45
  MASK_ON: True
DATASETS:
  TEST: ("coco_generalized_zeroshot_val",)
DATALOADER:
  NUM_WORKERS: 4 # num_workers == batchsize_per_gpu
INPUT:
  CLIP_TRAIN_SIZE: 1024
  CUSTOM_AUG: ResizeLongLSJ
TEST:
  DETECTIONS_PER_IMAGE: 300  #test_topk_per_image
  IMS_PER_BATCH: 4 #every gpu has most 2 images  # change
OUTPUT_DIR: 'output/clipRpn'