_BASE_: "Fvlm_lvis_my_emb.yaml"
MODEL:
  BACKBONE:
    TYPE: "RN50"
  WEIGHTS: ""
  FPN:
    ADD_PE: False #!!!!!!
  RPN:
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level sum=5000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NMS_THRESH_TEST: 0.5
    BATCH_SIZE_PER_IMAGE: 512 
    SCORE_THRESH_TEST: 0.0
    NUM_CLASSES: 1203 # num of seen classes
  ROI_BOX_HEAD:
    USE_FOCAL_CE: False
    USE_SIGMOID_CE: False
    BASE_ALPHA: 0.35
    NOVEL_BETA: 0.65
DATASETS:
  TEST: ("lvis_v1_val",)
DATALOADER:
  NUM_WORKERS: 4 # num_workers == batchsize_per_gpu
INPUT:
  CLIP_TRAIN_SIZE: 1024
  CUSTOM_AUG: ResizeLongLSJ
TEST:
  DETECTIONS_PER_IMAGE: 300  #test_topk_per_image
  IMS_PER_BATCH: 4 #every gpu has most 2 images  # change
OUTPUT_DIR: 'output/clipRpn'