_BASE_: "Base_ov_mine.yaml"
MODEL:
  BACKBONE:
    SAM_TYPE: "vit_t"
    TYPE: "RN50"
  CLIP_TEXT_FEATS_PATH: "datasets/lvis/lvis_base_cls.pkl" #********
  SAM_WEIGHTS: "mobile_sam.pt"
  PROPOSAL_GENERATOR:
    NAME: "SAMRPN"
  SAM_PIXEL_MEAN: [123.675, 116.280, 103.530]
  SAM_PIXEL_STD: [58.395, 57.12, 57.375]
  RPN:
    HEAD_NAME: "StandardRPNHead"
    POST_NMS_TOPK_TEST: 300
    BATCH_SIZE_PER_IMAGE: 256 # the sampling num 
  ROI_HEADS:
    NUM_CLASSES: 866
    BATCH_SIZE_PER_IMAGE: 32 #the sampling num 
  ROI_BOX_HEAD:
    BACKGROUND_WEIGHT: 0.9
    IGNORE_ZERO_CATS: True
    USE_FED_LOSS: False
    BASE_ALPHA: 0.35
    NOVEL_BETA: 0.65
    CAT_FREQ_PATH: ''
  ROI_MASK_HEAD:
    NAME: "samMaskHead"
    WITH_SINCOS: True
    MASK_LOSS_TYPE: "ce_dice" 
    PER_QUERY_POINT: 4 # 采样点
    SELECT_FORE_CLS: False # !!!!
    BOX_PROMPTER: False # !!!!! 
    ADD_PE_CONTEXT: True # !!!!!
    IOU_LOSS_WEIGHT: 0. # !!!!
    ADD_PE_BEFORE_POOL: True # !!!!
    ROI_PROMPTER: "CLIP" #!!!!
    IN_FEATURES: ["feat2", "feat3", "feat4", "feat5"]
  MASK_ON: True
  SAM_ON: True
  NUM_SAMPLE_CATS: 50
DATASETS:
  TRAIN: ("lvis_v1_zeroshot_train",)
  TEST: ("lvis_v1_val",)
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.001
  NUM_WORKERS: 16 # num_workers == batchsize_per_gpu
SOLVER:
  IMS_PER_BATCH: 32  # change  # max 8 imgs per batch
  BASE_LR: 0.0036  # change0.000025
  MAX_ITER: 46100
  CHECKPOINT_PERIOD: 900000  #  change
  OPTIMIZER: 'ADAMW'
  WEIGHT_DECAY: 0.0001
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  WARMUP_FACTOR: 0.16
  WARMUP_METHOD: "linear" 
  WARMUP_ITERS: 2000
  # STEPS: (20250, 21375, 21738)
  GAMMA: 0.1
  MOMENTUM: 0.9
INPUT:
  CLIP_TRAIN_SIZE: 1024
  CUSTOM_AUG: ResizeLongLSJ2  #!!!!
OUTPUT_DIR: './output/clipRpn/SamOnLvis'