_BASE_: "Base_ov_mine.yaml"
MODEL:
  BACKBONE:
    TYPE: "vit_t"
    CLIP_TYPE: "RN50"
  CLIP_TEXT_FEATS_PATH: "datasets/lvis/lvis_cls.pkl" #********
  SAM_WEIGHTS: "mobile_sam.pt"
  PROPOSAL_GENERATOR:
    NAME: "SAMRPN"
  SAM_PIXEL_MEAN: [123.675, 116.280, 103.530]
  SAM_PIXEL_STD: [58.395, 57.12, 57.375]
  RPN:
    HEAD_NAME: "StandardRPNHead"
    POST_NMS_TOPK_TEST: 300
    BATCH_SIZE_PER_IMAGE: 256 # the sampling num 
  ROI_HEADS:
    FPN_PE: "fixed" # !!!!!
    SCORE_THRESH_TEST: 0.02
    NUM_CLASSES: 1203
    NMS_THRESH_TEST: 0.5
    BATCH_SIZE_PER_IMAGE: 32 #the sampling num 
  ROI_BOX_HEAD:
    BACKGROUND_WEIGHT: 0.9
    TRAIN_ON_PRED_BOXES: False
    USE_FED_LOSS: False
    BASE_ALPHA: 0.35
    NOVEL_BETA: 0.65
    CAT_FREQ_PATH: 'datasets/lvis/lvis_v1_train_norare_cat_info.json'
  ROI_MASK_HEAD:
    NAME: "samMaskHead"
    WITH_SINCOS: True
    MASK_LOSS_TYPE: "ce_dice" 
    PER_QUERY_POINT: 4 # 采样点
    SELECT_FORE_CLS: False # !!!!
    BOX_PROMPTER: False # !!!!! 
    ADD_PE_CONTEXT: True # !!!!!
  MASK_ON: True
  NUM_SAMPLE_CATS: 50
  SAM_ON: True
DATASETS:
  TRAIN: ("lvis_v1_train_norare",)
  TEST: ("lvis_v1_val",)
DATALOADER:
  NUM_WORKERS: 16 # num_workers == batchsize_per_gpu
SOLVER:
  IMS_PER_BATCH: 256  # change  # max 8 imgs per batch
  BASE_LR: 0.0036  # change0.000025
  MAX_ITER: 46100
  CHECKPOINT_PERIOD: 900000  #  change
  OPTIMIZER: 'SGD'
  WEIGHT_DECAY: 0.0001
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  WARMUP_FACTOR: 0.16
  WARMUP_METHOD: "linear" 
  WARMUP_ITERS: 2000
  STEPS: (20250, 21375, 21738)
  GAMMA: 0.1
  MOMENTUM: 0.9
INPUT:
  CLIP_TRAIN_SIZE: 1024
  CUSTOM_AUG: ResizeLongLSJ2  #!!!!
TEST:
  DETECTIONS_PER_IMAGE: 300  #test_topk_per_image
  EVAL_PERIOD: 90000 # change
  IMS_PER_BATCH: 1 #every gpu has most 2 images  # change
  SCORE_TYPE: 'cls'
  GEOMETRIC_FACT: 0.65
OUTPUT_DIR: './output/clipRpn/SamOnLvis'