_BASE_: "Base_ov_mine.yaml"
MODEL:
  BACKBONE:
    TYPE: "vit_t"
    CLIP_TYPE: "ViT-B/16"
  WEIGHTS: "mobile_sam.pt"
  PROPOSAL_GENERATOR:
    NAME: "SAMRPN"
  RPN:
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 300
    BATCH_SIZE_PER_IMAGE: 256
  ROI_HEADS:
    BATCH_SIZE_PER_IMAGE: 64
  ROI_BOX_HEAD:
    BBOX_REG_WEIGHTS: (10.0, 10.0, 5.0, 5.0)
    IGNORE_ZERO_CATS: True # freq_weight for lvis
    CAT_FREQ_PATH: 'datasets/coco/zero-shot/instances_train2017_seen_2_oriorder_cat_info.json'
  ROI_MASK_HEAD:
    NAME: "samMaskHead"
    WITH_SINCOS: True
    MASK_LOSS_TYPE: "ce_dice" 
    PER_QUERY_POINT: 4
  MASK_ON: True
DATASETS:
  TRAIN: ("coco_zeroshot_train_oriorder",)
  TEST: ("coco_generalized_zeroshot_val",)
DATALOADER:
  NUM_WORKERS: 4 # num_workers == batchsize_per_gpu
SOLVER:
  IMS_PER_BATCH: 16  # change  # max 8 imgs per batch
  BASE_LR: 0.0005  # change0.000025
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 5000  #  change
INPUT:
  CLIP_TRAIN_SIZE: 224
TEST:
  DETECTIONS_PER_IMAGE: 300  #test_topk_per_image
  EVAL_PERIOD: 90000 # change
  IMS_PER_BATCH: 1 #every gpu has most 2 images  # change
  SCORE_TYPE: 'ob_geo_cls'
  GEOMETRIC_FACT: 0.35
OUTPUT_DIR: './output/ovcoco'
VIS_PERIOD: 20