_BASE_: "Base_ov_mine.yaml"
MODEL:
  BACKBONE:
    TYPE: "vit_t"
    CLIP_TYPE: "RN50"
  CLIP_TEXT_FEATS_PATH: "datasets/coco/coco_cls.pkl"
  WEIGHTS: "mobile_sam.pt"
  RPN:
    HEAD_NAME: "StandardRPNHead"
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 300
  ROI_HEADS:
    NMS_THRESH_TEST: 0.4
    BATCH_SIZE_PER_IMAGE: 512 
  ROI_BOX_HEAD:
    BBOX_REG_WEIGHTS: (10.0, 10.0, 5.0, 5.0)
    IGNORE_ZERO_CATS: True # freq_weight for lvis
    CAT_FREQ_PATH: 'datasets/coco/zero-shot/instances_train2017_seen_2_oriorder_cat_info.json'
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
  # ROI_MASK_HEAD:
  #   NAME: "samMaskHead"
  #   WITH_SINCOS: True
  #   MASK_LOSS_TYPE: "ce_dice" 
  #   PER_QUERY_POINT: 4
  # MASK_ON: True
DATASETS:
  TRAIN: ("coco_zeroshot_train_oriorder",)
  TEST: ("coco_generalized_zeroshot_val",)
DATALOADER:
  NUM_WORKERS: 16 # num_workers == batchsize_per_gpu
SOLVER:
  IMS_PER_BATCH: 64  # change  # max 8 imgs per batch
  BASE_LR: 0.02  # change0.000025
  MAX_ITER: 11250
  CHECKPOINT_PERIOD: 5000  #  change
  OPTIMIZER: 'SGD'
  WEIGHT_DECAY: 0.01
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  WARMPUP_FACTOR: 0.16
  WARMUP_METHOD: "constant"
  WARMUP_ITERS: 1000
  STEPS: (10125, 10688, 10869)
  GAMMA: 0.1
INPUT:
  CLIP_TRAIN_SIZE: 1024
  CUSTOM_AUG: ResizeLongLSJ
TEST:
  DETECTIONS_PER_IMAGE: 300  #test_topk_per_image
  EVAL_PERIOD: 11250 # change
  IMS_PER_BATCH: 1 #every gpu has most 2 images  # change
  SCORE_TYPE: 'ob_geo_cls'
  GEOMETRIC_FACT: 0.35
OUTPUT_DIR: './output/ovcoco'