_BASE_: "OpenDet_tiny_lvis.yaml"
MODEL:
  BACKBONE:
    SAM_TYPE: "vit_t"
    TYPE: "RN50"
  CLIP_TEXT_FEATS_PATH: "datasets/lvis/lvis_cls.pkl" #********
  SAM_WEIGHTS: "mobile_sam.pt"
  WEIGHTS: ""
  SAM_PIXEL_MEAN: [123.675, 116.280, 103.530]
  SAM_PIXEL_STD: [58.395, 57.12, 57.375]
  RPN:
    POST_NMS_TOPK_TEST: 500
    BATCH_SIZE_PER_IMAGE: 256 # the sampling num 
  ROI_HEADS:
    NUM_CLASSES: 1203
    NMS_THRESH_TEST: 0.5
    BATCH_SIZE_PER_IMAGE: 32 #the sampling num 
  ROI_BOX_HEAD:
    USE_FED_LOSS: False
    BASE_ALPHA: 0.35
    NOVEL_BETA: 0.65
    CAT_FREQ_PATH: ''
  ROI_MASK_HEAD:
    NAME: "samMaskHead"
    WITH_SINCOS: True
    MASK_LOSS_TYPE: "ce_dice" 
    PER_QUERY_POINT: 4 # 采样点
    BOX_PROMPTER: 'Roi' # !!!!!
    SELECT_FORE_CLS: False # !!!!
    ADD_PE_CONTEXT: True # !!!!!
    IOU_LOSS_WEIGHT: 0. # !!!!
    ADD_PE_BEFORE_POOL: True # !!!!
    ROI_PROMPTER: "SAM" # SAM/CLIP/FUSE
    CONTEXT_FORMER_LAYER: 'DetrDecoderLayer' # !!!!
  NUM_SAMPLE_CATS: 50
DATASETS:
  TEST: ("lvis_v1_val",)
DATALOADER:
  NUM_WORKERS: 2 # num_workers == batchsize_per_gpu
INPUT:
  CLIP_TRAIN_SIZE: 1024
  CUSTOM_AUG: ResizeLongLSJ2  #!!!!
TEST:
  DETECTIONS_PER_IMAGE: 300  #test_topk_per_image
  EVAL_PERIOD: 90000 # change
  IMS_PER_BATCH: 1 #every gpu has most 2 images  # change
  SCORE_TYPE: 'cls'
  GEOMETRIC_FACT: 0.65
  USE_IOU_SCORE: False
  FIXED_AP: False
OUTPUT_DIR: './output/clipRpn/SamOnLvis'
EVAL_AR: False
