_BASE_: "RSPrompter_anchor.yaml"
MODEL:
  BACKBONE:
    TYPE: "vit_b"
  WEIGHTS: "/opt/tiger/OpenVo-Seg-master_tmp/output/full_optimize_wo_mask_768/model_final.pth"
  RPN:
    PRE_NMS_TOPK_TEST: 12000  # Per FPN level
    POST_NMS_TOPK_TEST: 12000
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.05
    NMS_THRESH_TEST: 0.5
    ALLOW_LOW_QUALITY_MATCHES: False  #
    PROPOSAL_APPEND_GT: True
  MASK_ON: False
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
DATALOADER:
  NUM_WORKERS: 2 #num_workers == batchsize_per_gpu
INPUT:
  TEST_INPUT_TYPE: ResizeLongestSize
TEST:
  DETECTIONS_PER_IMAGE: 1000  #test_topk_per_image
  MASK_THR_BINARY: 0.5  
  IMS_PER_BATCH: 1 #every gpu has most 2 images  # change
VERSION: 2
FP16: True
