_BASE_: "RSPrompter_anchor.yaml"
MODEL:
  BACKBONE:
    TYPE: "vit_b"
  WEIGHTS: "output/Detic-COCO/RSPrompter_anchor/model_0089999.pth"
  RPN:
    PRE_NMS_TOPK_TEST: 6000  # Per FPN level
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    SCORE_THRESH_TEST: 0.05
    NMS_THRESH_TEST: 0.5
    ALLOW_LOW_QUALITY_MATCHES: False  #
    PROPOSAL_APPEND_GT: True
  MASK_ON: False
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
DATALOADER:
  NUM_WORKERS: 2 #num_workers == batchsize_per_gpu
INPUT:
  TEST_INPUT_TYPE: ResizeLongestSize
TEST:
  DETECTIONS_PER_IMAGE: 100  #test_topk_per_image
  MASK_THR_BINARY: 0.5  
  IMS_PER_BATCH: 4 #every gpu has most 2 images  # change
VERSION: 2
FP16: True
